### ISSUE TITLE
Evolution of saveFHIRResources

### ISSUE THREAD

**Issue by ruscoder** [beda-software/aidbox-react#10]
We have a very useful helper saveFHIRResources, but we can't do conditional operations or use patch.

I suggest adding helper `applyFHIRBundle(resourcesDescriptors, type=transaction|batch)`
where resourcesDescriptors is a list of {resource, method: POST/PUT/PATCH, ifMatch, ifNoneMatch,  ifModifiedSince, ifNoneExist}  for details see https://www.hl7.org/fhir/bundle.html and https://www.hl7.org/fhir/http.html 

But also we need some extra helpers:

* read(resource, cond headers such as ifModifiedSince)
* create(resource, cond headers)
* patch(resource, cond headers)
* update(resource, cond headers)
* delete(resource, cond headers)

As a result, we can use it in a following way:
```
await applyFHIRBundle([create(res1), patch(res2), update(res3, ifMatch: res3.meta.versionId))], type='transaction')
```

**Comment by ruscoder** [comment]
Ideas:
* ifMatch is usually used with resource.meta.versionId, so it can be just a flag
* ifMatch, ifNoneMatch usually receives a query string, so we can pass search params here as SearchParam[] and transform to query string
* ifModifiedSince receives string with date - there is nothing to change

**Comment by ruscoder** [comment]
We have getFHIRResource, getFHIRResources, saveFHIRResource, patchFHIRResource, deleteFHIRResource, forceDeleteFHIRResource.

What about using them in single-mode and as part of the bundle? 


Let's consider possible architecture.

```
createFHIRResource(resource,  {conditional search params}) - generate id on the frontend if not provided and always use PUT /ResourceType
updateFHIRResource(resource, {conditional search params}) - version aware check, if resource.id is not provided use PUT /ResourceType otherwise use PUT /ResourceType/id with If-Match header
patchFHIRResource(resource, {conditional search params}) - version aware check, the same as update
deleteFHIRResource(resource) - the same as now
forceDeleteFHIRResource()
```

let's put them into applyBundle()
```
const appointment = {id: 'existingappid1', ...};

const encounter = {id: 'encid1', status: 'planned', appointment: getReference(appointment), ...};
```

Not in a bundle:
```
await createFHIRResource(encounter, {'episode-of-care': eoc.id, status: 'planned'})
await patchFHIRResource(appointment, {'status': 'fulfilled'})
```

In a bundle:
```
await applyBundle([
    createFHIRResource(encounter, {'episode-of-care': eoc.id, status: 'planned'}),
    patchFHIRResource(appointment, {'status': 'fulfilled'})
])
```

and it some-how should work. I'm not sure that it is possible, but we should use the same interface for in-bundle and ordinary helpers

**Comment by ruscoder** [comment]
## Proposal 1.
### Pure functions:
#### Fetching
* getResource()
* findResource()
* getResources()

#### Manipulating
* createResource()
* updateResource()
* patchResource()
* deleteResource()
* forceDeleteResource()

### Invocation
* await applyFHIRService(srv1())
* await applyFHIRServices([srv1(), srv2()], type='transaction')

**Comment by ruscoder** [comment]
## Proposal 2.

### Full backward compatibility
#### Fetching
* await getFHIRResource()
* await findFHIRResource()
* await getFHIRResources()

#### Manipulating
* await createFHIRResource()
* await updateFHIRResource()
* await patchFHIRResource()
* await deleteFHIRResource()
* await forceDeleteFHIRResource()

### Pure functions (new)
* create()
* update()
* patch()
* delete()
* forceDelete()
where create, delete, forceDelete, patch, update have the same interface as *FHIRResource methods
and maybe (analogues for getFHIRResource, getFHIRResources) - may be useful when you want to make a query with long query params
* get(ref)
* list(resourceType, searchParams)

### Execution
* await applyFHIRService(create())
* await applyFHIRServices([create(), delete(), forceDelete(), patch(), update()], type='transaction|batch')

**Comment by ruscoder** [comment]
Let's do proposal 2 with backward compatibility (don't remove old functions).

Signature of functions:
```
create<T extends AidboxResource>(resource: T, conditionalSearchParams?: SearchParams): T
makes POST to /${resource.resourceType}?expanded conditionalSearchParams

update<T extends AidboxResource>(resource: T, conditionalSearchParams?: SearchParams): T
makes PUT to /${resource.resourceType}?expanded conditionalSearchParams if conditionalSearchParams present otherwise PUT  /${resource.resourceType}/${resource.id}


patch<T extends AidboxResource>(resource: Partial<T>, conditionalSearchParams?: SearchParams)
the same as update, but with PATCH method

delete(reference: AidboxReference, conditionalSearchParams?: SearchParams)
the same as deleteFHIRResource now

forceDelete(reference: AidboxReference, conditionalSearchParams?: SearchParams)
the same as update, but with DELETE method

get<T>(reference: AidboxReference<T>): T
makes  GET /${reference.resourceType}/${reference.id}

list<T>(resourceType: string, searchParams?: SearchParams): Bundle<T>
make GET /${resourceType}?expanded searchParams

```

**Comment by ufocoder** [comment]
@ruscoder by the way `delete` is the [ reserved word](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords) :(
